service: s3-lambda-resize

custom:
  bucketName: s3-lambda-resize-photos

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: "arn:aws:s3:::${self:custom.bucketName}/*"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  resize:
    name: ${self:provider.stage}-resize
    handler: src/resize.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
