service: s3-lambda-resize-api

provider:
  name: aws
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::s3-lambda-resize-dev-uploads/*'
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:
  getPresignUrl:
    handler: src/main.handler
    events:
      - http:
          path: /presign-url
          method: GET
          cors: true
  getImageLinks:
    handler: src/main.handler
    events:
      - http:
          path: /image/{id}
          method: GET
          cors: true
  # If you want to have all routes under a single lambda (for your whole app), use the solution below
  # other:
  #   handler: src/main.handler
  #   events:
  #     - http:
  #         path: /
  #         method: ANY
  #         cors: true
  #     - http:
  #         path: /{proxy+}
  #         method: ANY
  #         cors: true
